version: "3.9"

services:
  api:
    container_name: noroff_agency_api
    restart: on-failure
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - noroff
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15-alpine
    restart: on-failure
    container_name: noroff_agency_api_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    networks:
      - noroff

volumes:
  postgres_storage:

networks:
  noroff:
